spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:armancaladb
    username: sa
    password: passme
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
